version: '3.9'

x-database-variables: &database-variables
  MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
  MYSQL_DATABASE: ${MYSQL_DATABASE}
  MYSQL_USER: ${MYSQL_USER}
  MYSQL_PASSWORD: ${MYSQL_PASSWORD}

services:
  database:
    container_name: database
    image: mysql:8.0
    volumes:
      - page_data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment: *database-variables
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 2s
      retries: 20
  backend:
    image: ${DOCKER_USERNAME}/${DOCKER_IMAGE_BACKEND}
    container_name: backend
    environment:
      <<: *database-variables
      APP_PORT: ${APP_PORT}
      MYSQL_HOST: ${MYSQL_HOST}
      FILES_UPLOAD_PATH: ${FILES_UPLOAD_PATH}
    volumes:
      - ./upload:/upload
    depends_on:
      database:
        condition: service_healthy
  nginx:
    image: ${DOCKER_USERNAME}/${DOCKER_IMAGE_NGINX}
    container_name: nginx
    ports:
      - "80:8888"
    volumes:
      - ./nginx/images:/static_files/images
      - ./upload/customers_images:/static_files/images/customers_images
    depends_on:
      - backend

volumes:
  page_data: